furnidashboard/datetimepicker/urls.py
from django.conf.urls import url

from .views import JSTemplateView


urlpatterns = [url(r'^loader.js',
               JSTemplateView.as_view(),
               name='datetimepicker-loader')]

furnidashboard/claims/models.py
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from django.utils import formats
from audit_log.models import AuthStampedModel
from orders.models import Order, OrderItem
from customers.models import Customer


class Claim(TimeStampedModel, AuthStampedModel):
    """
    A model class representing the Claim information for sold orders/items
    """

    PAID_BY_CHOICES = (
        ('VND', 'Vendor'),
        ('FURN', 'Furnitalia'),
        ('CUST', 'Customer'),
    )

    CLAIM_VENDORS = (
        ('NTZ', 'Natuzzi Italia'),
        ('EDITIONS', 'Natuzzi Editions'),
        ('REVIVE', "Natuzzi Re-Vive"),
        ('SOFTALY', "Softaly"),
    )

    claim_date = models.DateTimeField(null=False)
    claim_desc = models.TextField(blank=True, null=False, default='')
    delivery_date = models.DateField(null=True, blank=True)
    item_origin = models.CharField(null=False, blank=False, choices=CLAIM_VENDORS, max_length=128)
    vendor_claim_no = models.CharField(null=False, blank=True, default='', max_length=128)
    customer = models.ForeignKey(Customer, default=None, blank=True, null=True, on_delete=models.CASCADE)
    order_ref = models.ForeignKey(Order, default=None, blank=True, null=True, on_delete=models.CASCADE)
    order_invoice_num = models.CharField(null=False, blank=True, default='', max_length=250)
    amount = models.FloatField(blank=True, default=0.0)
    paid_by = models.CharField(null=False, blank=True, default='', choices=PAID_BY_CHOICES, max_length=128)
    repair_tech = models.CharField(null=False, blank=True, default='', max_length=128)

    def __unicode__(self):
        return "Claim: #%s, date:%s, customer:%s" % (
            self.pk, formats.date_format(self.claim_date, 'DATE_FORMAT_SHORT'), str(self.customer))

    def get_absolute_url(self):
        return reverse("claim_detail", kwargs={"pk": self.pk})

    class Meta:
        db_table = "claims"
        ordering = ["-claim_date"]
        permissions = (
            ("view_claims", "Can View Claims"),
            ("edit_claims", "Can Edit Claims"),
        )


class ClaimStatus(TimeStampedModel, AuthStampedModel):
    """
    A model class representing the Statuses for a claim 
    """
    CLAIM_STATUSES = (
        ('NEW', 'New'),
        ('SUBMITTED', 'Submitted'),
        ('AUTHORIZED', 'Authorized'),
        ('FUNDED', 'Funded'),
        ('RECEIVED', 'Received'),
        ('CANCELLED', 'Cancelled'),
    )

    claim = models.ForeignKey(Claim, on_delete=models.CASCADE)
    status = models.CharField(null=False, blank=False, choices=CLAIM_STATUSES, max_length=128)
    date = models.DateTimeField(null=False, blank=False)
    status_desc = models.CharField(null=False, default='', blank=True, max_length=250)

    def __unicode__(self):
        return "Claim Status: %s, date=%s, claim #%s" % (
            self.get_status_display(), formats.date_format(self.date, 'DATE_FORMAT_SHORT'), self.claim.pk)

    class Meta:
        db_table = "claim_status"
        ordering = ["-date"]


class ClaimPhoto(models.Model):
    """
    A model class for storing Claim photos
    """

    claim = models.ForeignKey(Claim, on_delete=models.CASCADE)
    file = models.FileField(upload_to='claims/%Y/%m')
    description = models.CharField(max_length=255, blank=True, null=False, default='')

    @property
    def filename(self):
        import os
        return os.path.basename(self.file.name)

    @property
    def file_extension(self):
        import os.path
        name, extension = os.path.splitext(self.file.name) #[1][1:].strip()
        return extension[1:].strip()

    def __unicode__(self):
        if len(self.description):
            return self.description
        else:
            return ""

    class Meta:
        db_table = "claim_photos"


class VendorClaimRequest(models.Model):
    """
    A model class for storing Claims submitted
    to vendors.
    """

    claim = models.ForeignKey(Claim, on_delete=models.CASCADE)
    file = models.FileField(upload_to='claims/%Y/%m', blank=True)
    data_fields = models.TextField(null=False, blank=True, default='')

    def __unicode__(self):
        return "Vendor Claim Request form #%d, claim #%d" % (self.pk, self.claim_id)

    class Meta:
        db_table = "claim_vendor_requests"

furnidashboard/claims/views.py
from django.conf import settings
from django.core.files import File
# from django.core.files.temp import TemporaryFile
from tempfile import TemporaryFile
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse
import django_tables2 as tables
from django_tables2 import RequestConfig, SingleTableView
from django.contrib import messages
from core.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.utils import timezone
from claims.models import Claim, ClaimStatus, ClaimPhoto, VendorClaimRequest
from claims.tables import ClaimsTable
import claims.utils as claim_utils
import claims.forms as claim_forms
from datetime import datetime, timedelta
from django.http import HttpResponse
from pdf import pdf
import core.utils as core_utils
import json


class ClaimsTableView(LoginRequiredMixin, SingleTableView):
    model = Claim
    table_class = ClaimsTable
    template_name = "claims/claims_table.html"

    def get_queryset(self):
        qs = Claim.objects.all()\
                .select_related('customer')\
                .select_related('order_ref')\
                .select_related('order_ref__customer')\
                .prefetch_related('claimstatus_set')
        # try:
        #     status = self.request.GET['status_filter']
        #     qs = claim_utils.filter_claims_by_latest_status(qs, status)
        # except KeyError, e:
        #     pass
        #
        # try:
        #     date_range = self.request.GET['date_range']
        #     self.from_date, self.to_date = core_utils.get_date_range_from_string(date_range)
        #     lookup_kwargs = {
        #         '%s__gte' % 'claim_date': self.from_date -  timedelta(minutes=1),
        #         '%s__lt' % 'claim_date': self.to_date,
        #     }
        #     qs = qs.filter(**lookup_kwargs)
        # except KeyError, e:
        #     pass

        return qs


class ClaimDetailView(LoginRequiredMixin, DetailView):
    model = Claim
    context_object_name = "claim"
    template_name = "claims/claim_detail.html"


class ClaimCreateView(PermissionRequiredMixin, CreateView):
    """
	Claim Creation view. Presents blank forms for creation of new claims.
	"""

    model = Claim
    template_name = "claims/claim_update.html"
    context_object_name = "claim"
    form_class = claim_forms.ClaimForm

    required_permissions = (
        'claims.edit_claims',
    )

    def get(self, request, *args, **kwargs):
        """
		Handle GET requests and instantiate blank version of the form
		and it's inline formsets
		"""

        cur_date = timezone.make_aware(datetime.now(), timezone.get_current_timezone())
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        form.fields['claim_date'].initial = cur_date

        status_initial = [{
            'date': cur_date,
            'status': 'NEW',
            'status_desc': 'New claim entered'
        }]
        ClaimStatusFormSet = claim_forms.get_claim_status_formset(extra=1)
        claim_status_formset = ClaimStatusFormSet(prefix="status", initial=status_initial)

        ClaimPhotoFormSet = claim_forms.get_claim_photos_formset(extra=1)
        claim_photos_formset = ClaimPhotoFormSet(prefix="photos")

        extra_forms = {
            'form': form,
            'status_formset': claim_status_formset,
            'photos_formset': claim_photos_formset,
        }
        context = self.get_context_data()
        context.update(extra_forms)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        """
		Handles POST requests, instantiates a form instance and its inline formsets with the passed POST variables
		and then checks them for validity
		"""

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        ClaimStatusFormSet = claim_forms.get_claim_status_formset(extra=1)
        claim_status_formset = ClaimStatusFormSet(self.request.POST, self.request.FILES, prefix="status")

        ClaimPhotoFormSet = claim_forms.get_claim_photos_formset(extra=1)
        claim_photos_formset = ClaimPhotoFormSet(self.request.POST, self.request.FILES, prefix="photos")

        extra_forms = {
            'form': form,
            'status_formset': claim_status_formset,
            'photos_formset': claim_photos_formset,
        }

        if form.is_valid() and claim_status_formset.is_valid() and claim_photos_formset.is_valid():
            return self.form_valid(**extra_forms)
        else:
            messages.add_message(self.request, messages.ERROR, "Error saving Claim information",
                                 extra_tags="alert alert-danger")
            return self.form_invalid(**extra_forms)

    def form_valid(self, *args, **kwargs):
        """
		Called if all forms are valid. Creates a Claim instance along with associated info
		and then redirects to a success page
		"""
        form = kwargs['form']
        status_formset = kwargs['status_formset']
        photos_formset = kwargs['photos_formset']

        self.object = form.save(commit=False)

        # save order
        self.object.save()

        # save status
        if status_formset.has_changed():
            status_formset.instance = self.object
            status_formset.save()

        # save photos
        if photos_formset.has_changed():
            photos_formset.instance = self.object
            photos_formset.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('claim_detail', kwargs={'pk': self.object.pk})

    def form_invalid(self, *args, **kwargs):
        """
		Called if any of the forms on order page is invalid. Returns a response with an invalid form in the context
		"""
        context = self.get_context_data()
        context.update(kwargs)
        return self.render_to_response(context)


class ClaimUpdateView(PermissionRequiredMixin, UpdateView):
    """
	Claim Update view.
	"""

    model = Claim
    context_object_name = "claim"
    template_name = "claims/claim_update.html"
    form_class = claim_forms.ClaimForm

    required_permissions = (
        'claims.edit_claims',
    )

    def get(self, request, *args, **kwargs):
        """
		Handle GET requests and instantiate blank version of the form
		and it's inline formsets
		"""
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        extra = 1 if self.object.claimstatus_set.count() == 0 else 0  # if no statuses were entered for the claim, add a blank form
        ClaimStatusFormSet = claim_forms.get_claim_status_formset(extra=extra)
        claim_status_formset = ClaimStatusFormSet(instance=self.object, prefix="status")

        extra = 1  # if self.object.claimphoto_set.count() == 0 else 0  #if no statuses were entered for the claim, add a blank form
        ClaimPhotoFormSet = claim_forms.get_claim_photos_formset(extra=extra)
        claim_photos_formset = ClaimPhotoFormSet(instance=self.object, prefix="photos")

        extra_forms = {
            'form': form,
            'status_formset': claim_status_formset,
            'photos_formset': claim_photos_formset,
        }
        context = self.get_context_data()
        context.update(extra_forms)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        """
		Handles POST requests, instantiates a form instance and its inline formsets with the passed POST variables
		and then checks them for validity
		"""

        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        ClaimStatusFormSet = claim_forms.get_claim_status_formset(extra=1)
        claim_status_formset = ClaimStatusFormSet(self.request.POST, self.request.FILES, instance=self.object,
                                                  prefix="status")

        ClaimPhotoFormSet = claim_forms.get_claim_photos_formset(extra=1)
        claim_photos_formset = ClaimPhotoFormSet(self.request.POST, self.request.FILES, instance=self.object,
                                                 prefix="photos")

        extra_forms = {
            'form': form,
            'status_formset': claim_status_formset,
            'photos_formset': claim_photos_formset,
        }

        if form.is_valid() and claim_status_formset.is_valid() and claim_photos_formset.is_valid():
            return self.form_valid(**extra_forms)
        else:
            messages.add_message(self.request, messages.ERROR, "Error saving Claim information",
                                 extra_tags="alert alert-danger")
            return self.form_invalid(**extra_forms)

    def form_valid(self, *args, **kwargs):
        """
		Called if all forms are valid. Creates a Claim instance along with associated info
		and then redirects to a success page
		"""
        form = kwargs['form']
        status_formset = kwargs['status_formset']
        photos_formset = kwargs['photos_formset']

        self.object = form.save(commit=False)

        # save order
        self.object.save()

        # save status
        if status_formset.has_changed():
            status_formset.instance = self.object
            status_formset.save()

        # save photos
        if photos_formset.has_changed():
            photos_formset.instance = self.object
            photos_formset.save()

        return HttpResponseRedirect(self.get_success_url())

    # return self.form_invalid(**kwargs)

    def get_success_url(self):
        return reverse('claim_detail', kwargs={'pk': self.object.pk})

    def form_invalid(self, *args, **kwargs):
        """

furnidashboard/templates/claims/claim_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete Claim{% endblock %}

{% block page_title %} Confirm Claim Deletion{% endblock page_title %}

{% block content %}

<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock content %}

furnidashboard/templates/claims/claim_detail.html
{% extends "base.html" %}

{% load extras %}
{% block title %}Claim #{{claim.pk}} Detail{% endblock %}

{% block page_title %}Claim #{{claim.pk}} Detail{% endblock page_title %}

{% block content %}
  
    <div class="well hidden-print">
        {% if perms.claims.edit_claims %}
            <a href="{% url 'claim_edit' claim.pk %}" title="Edit Claim">Update Claim</a>
            |  <a href="{% url 'claim_delete' claim.pk %}" title="Delete Claim">Delete this Claim</a>
        {% endif %}
    </div>

    <hr/>

    <h3>Claim Info</h3>
  
    <div class="panel panel-default">
        <div class="panel-body">

            <div class="col-md-2">
                <h4>Claim Date:</h4>
                {{claim.claim_date|date:'j F, Y'}}
            </div>
            <div class="col-md-4">
                <h4>Claim Description:</h4>
                {{claim.claim_desc}}
            </div>
            <div class="col-md-2">
                <h4>Delivery Date:</h4>
                {{claim.delivery_date|date:'j F, Y'}}
            </div>

             <div class="col-md-2">
                <h4>Customer:</h4>
                {{claim.customer}}
             </div>

      
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-2">
                <h4>Amount:</h4>
                ${{claim.amount}}
            </div>

            <div class="col-md-2">
                <h4>Paid by:</h4>
                {{claim.paid_by}}
            </div>

            <div class="col-md-6">
                <h4>Claim Status:</h4>
                {% if claim.claimstatus_set.count %}
                    <table id="order-issues-table" class="table table-striped table-bordered">
                        <thead>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Description</th>
                        </thead>
                        <tbody>
                            {% for status in claim.claimstatus_set.all %}
                                <tr
                                        {% ifequal forloop.counter 1  %}
                                            class="success"
                                        {% else %}
                                            style="background-color:lightgray;color:grey;"
                                        {% endifequal %}
                                >
                                    <td>{{ status.date|date:'j F, Y' }}</td>
                                    <td>{{ status.get_status_display|upper }}</td>
                                    <td> {{ status.status_desc }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No status entered.</p>
                {% endif %}

            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">

            <div class="col-md-2">
                <h4>Item Origin:</h4>
                {{claim.get_item_origin_display}}
            </div>

            <div class="col-md-2">
                <h4>Vendor Claim #:</h4>
                {{claim.vendor_claim_no}}
            </div>

            <div class="col-md-2">
                <h4>Vendor Order/Invoice #:</h4>
                {{claim.order_invoice_num}}
            </div>

            <div class="col-md-2">
                <h4>FurniCloud Order:</h4>
                {{claim.order_ref}}
            </div>

            <div class="col-md-2">
                <h4>Repair technician:</h4>
                {{claim.repair_tech}}
            </div>

        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-12">
                <h4>Claim Photos:</h4>
                {% if claim.claimphoto_set.count %}
                    <table id="order-photo-table" class="table table-striped">
                        <thead>
                            <th>Photo</th>
                            <th>Description</th>
                        </thead>
                        <tbody>
                            {% for file in claim.claimphoto_set.all %}
                                <tr>
                                    <td>
                                        <a href="{{ MEDIA_URL }}{{file.file}}"  target="_blank">

                                            {% if file.file_extension in "jpg png jpeg gif JPG JPEG PNG GIF" %}
                                                <img src="{{ MEDIA_URL }}{{file.file}}" width="250" alt="{{ file.filename }}"/> {{ file.filename }}
                                            {% else %}
                                                {{ file.filename }}
                                            {% endif %}
                                        </a>
                                    </td>

                                    <td> {{ file.description}} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No files were uploaded.</p>
                {% endif %}

            </div>


        </div>
    </div>


    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-12">
                <h4>Vendor Claim Request Forms:</h4>
                {% if claim.vendorclaimrequest_set.count %}
                    <table id="order-photo-table" class="table table-striped">
                        <tbody>
                            {% for request_form in claim.vendorclaimrequest_set.all %}
                                <tr>
                                    <td>
                                        <a href="{{ MEDIA_URL }}{{request_form.file}}"  target="_blank">
                                            {{ request_form.file.name }} - Download
                                        </a>
                                        ID:#{{ request_form.pk }}
                                    </td>

                                    <td>
                                        <a href="{% url 'claim_request_delete' claim_pk=request_form.claim.pk pk=request_form.pk %}" >
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No vendor claims were created.</p>
                {% endif %}

                <a href="{% url 'claim_vendor_form_add' claim_pk=claim.pk %}" title="New Vendor Claim Request" class="btn btn-primary">New Vendor Claim Request</a>

            </div>


        </div>
    </div>

    <hr/>
  
 <div class="row pull-right">
    <h4>Audit Trail:</h4>
    <table id="order-audit-trail" class="table">
      <tr>
        <td>Created:</td><td> {{ claim.created|date:'j F, Y H:i' }}</td>
        <td>by:</td> <td>{{ claim.created_by }}</td>
      </tr>
      <tr>
        <td>Modified: </td><td>{{ claim.modified|date:'j F, Y H:i' }}</td>
        <td>by:</td><td> {{ claim.modified_by }}</td>
      </tr>
    </table>
  </div>

{% endblock content %}

furnidashboard/templates/claims/claim_list.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% block title %} Recent Claims {% endblock %}

{% block page_title %}Claims{% endblock page_title %}

{% block content %}

	{% if perms.claims.edit_claims %}
		<aside id="createOrderAside">
     		<a href="{% url 'claim_add' %}" class="btn btn-primary btn-default">Create Claim</a>
   		</aside>
	{% endif %}

  <div>
      <ul class="breadcrumb">
	      {% for object in object_list %}
	      <li>{{ object }} | <a href="{% url "customer_edit" object.pk %}">Edit</a></li>
	      {% endfor %}
      </ul>
  </div>

{% endblock content %}

furnidashboard/templates/claims/claim_update.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
  {% if page_title %}
    {{ page_title }}
  {% else %}
    Update Claim
  {% endif %}
{% endblock %}

{% block page_title %}
	{% if claim.pk %}
		Modify Claim #{{claim.pk}}
	{% else %}
		Create Claim
	{% endif %}
{% endblock page_title %}

{% block extra_js %}
  {{ form.media }}
  {{ status_formset.media }}
  {{ photo_formset.media }}

	<script src="{% static 'js/formhelper.js' %}"></script>
	<script src="{% static 'js/jquery.validate.extra.js' %}"></script>


	<script type="text/javascript">
 		$(function() {
    		$(document).ready(function() {

				var warnBeforeExit = true;

	  			$('#claimStatusTable tr').formset({
			      	prefix: '{{status_formset.prefix}}',
			      	addCssClass: 'btn btn-default add-row',
			      	addText: 'Add <span class="glyphicon glyphicon-plus-sign"></span>',
			      	deleteCssClass: 'deleteStatusRow-tr',
			      	added: function($form) {

			        	console.log('New Claim Status is created');

			        	$('.input-group-addon', $form).off('change');
			            $('.input-group-addon', $form).off('click');

		                $('.date', $form).each(function() {
		                  $(this).removeData('datepicker')
		                  $(this).datepicker(FurnFormHelper.dateTimePickerOptions);
		                });
                        $('select', $form).val('');
			      	}
	  			});

	  			$('#photos-fieldset div.photos-form').formset({
	  	          prefix: '{{photos_formset.prefix}}',
	  	          added: function($form) {

	  	            $('.input-group-addon', $form).off('change');
	  	            $('.input-group-addon', $form).off('click');

	  	            $('.date', $form).each(function() {
	  	              $(this).removeData('datepicker')
	  	              $(this).datepicker(FurnFormHelper.dateTimePickerOptions);
	  	            });
	  	          }
				});

				//disable warning message if Submit button was clicked
			    $("#submitButton").on('click', function () { warnBeforeExit = false; });
			    $("#orderForm").on('submit', function () { warnBeforeExit = false; });

				//show warning if page is about to be closed.
				window.onbeforeunload = function() {
					if (warnBeforeExit) {
						return "Are you sure you want to close this page? All unsaved changes might be lost.";
					}
				}

    		});
 		});
  </script>
{% endblock extra_js %}

{% block extra_css %}
  <style type="text/css">
      .delete-row {
          margin-left:5px;
      }
  </style>
{% endblock %}

{% block content %}

<form action="" method="POST" enctype="multipart/form-data" id="orderForm" role="form" class="form">
	{% csrf_token %}
	{{ form.non_field_errors }}
	{{ form.management_form }}

	<fieldset>
      <legend>Claim info</legend>

        <div class="row">
          <div class="col-md-3">
            {% bootstrap_field form.claim_date %}
          </div>

          <div class="col-md-5">
            {% bootstrap_field form.claim_desc form_group_class="claim-desc-comment"  %}
          </div>
        </div>
    </fieldset>


    <fieldset>
    	<legend>Claim Status</legend>
	    <div class="panel panel-default">
	    	<div class="panel-body">

	            {{ status_formset.management_form }}
	            {% if status_formset %}
	              {{ status_formset.non_field_errors }}
	              {% bootstrap_formset_errors status_formset %}

	              <table id="claimStatusTable" class="table table-condensed" cellspacing="0" width="100%">
	                <thead>
	                  <tr class="">
	                    <th>Status Date</th>
	                    <th>Status</th>
	                    <th>Status Description</th>
	                  </tr>
	                </thead>

	                <tbody>

	                  {% for form in status_formset %}
	                    <tr class="status_form form-row" id="{{ status_formset.prefix }}-{{forloop.counter}}-row">
	                      <td class="col-md-2">
	                        {% bootstrap_field form.date show_label=False %}
	                      </td>
	                      <td>
	                        {% bootstrap_field form.status form_group_class="claim-status" show_label=False %}
	                      </td>
	                      <td>
	                      	{% bootstrap_field form.status_desc form_group_class="claim-status-desc" show_label=False %}
	                        {{ form.id }}
	                        {% if status_formset.can_delete %}
	                          {{ form.DELETE }}
	                        {% endif %}
	                      </td>
	                    </tr>
	                  {% endfor %}

	                </tbody>
	              </table>
	            {% else %}
	                <div class="alert warning">No claim status entered yet.</div>
	            {% endif %}

	    	</div>
	    </div>
	</fieldset>

    <fieldset>
    	<legend>Claim Details</legend>

        <div class="row">
          <div class="col-md-3">
            {% bootstrap_field form.delivery_date %}
          </div>

          <div class="col-md-3">
            {% bootstrap_field form.item_origin %}
          </div>

          <div class="col-md-3">
            {% bootstrap_field form.vendor_claim_no %}
          </div>

        </div>

        <div class="row">
            <div class="col-md-3">
                {% bootstrap_field form.order_invoice_num %}
            </div>
            <div class="col-md-3">
                {% bootstrap_label "Order (FurniCloud)"  %}
                {% bootstrap_field form.order_ref show_label=False %}
            </div>
            <div class="col-md-3">
                {% bootstrap_field form.amount %}
            </div>
            <div class="col-md-3">
                {% bootstrap_field form.paid_by %}
            </div>
        </div>

        <hr/>

        <div class="row">
            <div class="col-md-3">
                {% bootstrap_label "Select Customer"  %}
                {% bootstrap_field form.customer show_label=False %}
            </div>
        </div>

    </fieldset>

 	<fieldset id="photos-fieldset">
    	<legend>Claim Files</legend>
		{{ photos_formset.management_form }}
        {% if photos_formset %}
        	{{ photos_formset.non_field_errors }}
            {% bootstrap_formset_errors photos_formset %}

        	{% for photos_form in photos_formset %}

				{% if forloop.counter|divisibleby:"2" %}
					<div class="row">
				{% endif %}
	        		<div class="col-md-6">
		        		<div class=" photos-form form-row" id="{{ photos_form.prefix }}-row"> <!-- panel panel-default -->
		        			<div>
		        				{% bootstrap_form photos_form layout='inline'%}
		        				{{ photos_form.id }}
		        			</div>

			             </div>
		             </div>
				 {% if forloop.counter|divisibleby:"2" %}
					</div>
				{% endif %}

        	{% endfor %}

        {% endif %}
    </fieldset>

 <br/><br/>

  <input type="submit" id="submitButton" class="btn btn-primary btn-large" value="Save"/>

</form>

{% endblock content %}

furnidashboard/templates/claims/claims_table.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% block title %}Claims{% endblock %}
{% block extra_css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
{% endblock %}

{% block page_title %}Recent Claims{% endblock page_title %}

{% block content %}

	{% if perms.claims.edit_claims %}
		<aside id="createOrderAside">
     		<a href="{% url 'claim_add' %}" class="btn btn-primary btn-default">Create Claim</a>
   		</aside>
	{% endif %}
	
	<div id="order-list" class="claim-list">
    	{% render_table table %}
	</div>
{% endblock %}

furnidashboard/templates/claims/vendorclaimrequest_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete Claim Request Form{% endblock %}

{% block page_title %} Confirm Claim Request Form Deletion{% endblock page_title %}

{% block content %}

<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete Claim Request #{{ object.pk }}?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock content %}