furnidashboard/datetimepicker/urls.py
from django.conf.urls import url

from .views import JSTemplateView


urlpatterns = [url(r'^loader.js',
               JSTemplateView.as_view(),
               name='datetimepicker-loader')]

furnidashboard/orders/models.py
from audit_log.models.managers import AuditLog
from django.db import models
from django.urls import reverse
from django.conf import settings
from audit_log.models import AuthStampedModel
from django.db.models import CASCADE
from django_extensions.db.models import TimeStampedModel
from core.date_utils import get_prev_month_date
from customers.models import Customer
from stores.models import Store
from orders.managers import OrderManager


class Order(TimeStampedModel, AuthStampedModel):
    """
    A model class representing Order data
    """

    class Meta:
        ordering = ["-order_date"]
        db_table = "order_info"
        permissions = (
            ("view_orders", "Can View Orders"),
            ("view_sales", "Can View Sales Reports"),
            ("update_status", "Can Update Order Status"),
            ("view_cabinetry_orders", "Can View Cabinetry Orders"),
            ("update_cabinetry_orders", "Can Update Cabinetry Orders"),
        )

    ORDER_STATUSES = (
        ('N', 'New'),
        ('NEW_SO', 'New SO'),
        ('QUOT', 'Quotation'),
        ('ORDERED', 'Ordered'),
        ('Q', 'Pending'),                                    # Deprecated
        ('H', 'On Hold'),                                    # Deprecated
        ('P', 'In Production'),                              # Deprecated
        ('T', 'In Transit'),                                 # Deprecated
        ('R', 'Received/ In Warehouse'),
        ('S', 'Scheduled for Delivery'),
        ('PARTIALLY_DELIVERED', 'Partially Delivered'),
        ('D', 'Delivered'),
        ('E', 'Cancelled'),
        ('X', 'Dummy'),                                      # Deprecated
        ('I', 'Historical (Excel Import)'),                  # Deprecated
        ('C', 'Closed'),                                     # Deprecated
    )
    ORDER_ACTIVE_STATUSES = ['N', 'NEW_SO',
                             'ORDERED', 'Q', 'P', 'T', 'R', 'S', 'PARTIALLY_DELIVERED', 'D']
    REFERRAL_SOURCES = (
        ('UNK', 'Unknown'),
        ('RVL', 'Roseville Store'),  # inactive
        ('POS', 'Purchased Before'),
        ('RET', 'Returning Customer'),  # inactive
        ('COP', 'Copenhagen Customer'),
        ('GOOG', 'Google Search'),
        ('EBL', 'E-Blast'),
        ('WEB', 'Website Direct Visit'),
        ('VENDOR', 'Vendor Website Referral'),
        ('TV', 'TV'),
        ('MAG', 'Magazine'),
        ('REF', 'Referred by friends/relatives'),
        ('SOC', 'Social networks'),
        ('BILL', 'Billboard/Sign/Drive-by'),
        ('CST', 'Referred by existing Furnitalia customer'),
        ('NWP', 'Newspaper'),
        ('EXPO', 'Home & Landscape Show'),
        ('NO', 'Not Referred'),
        ('OTH', 'Other (see comments)'),
    )

    ORDER_TYPES = (
        ('stock', 'In Stock Order'),
        ('special_order', 'Special Order'),
        ('quote', 'Quote'),
        ('cabinetry', 'German Kitchen & Bath'),
        ('cabinetry_quote', 'GermanKB Quote'),
        ('appliances', 'Appliances'),
        ('windows', 'Hunter Douglas'),
        ('design', 'Design'),
        ('flooring', 'Flooring'),
    )

    number = models.CharField(max_length=50)
    order_date = models.DateTimeField(null=True)
    customer = models.ForeignKey(
        Customer, related_name='orders', on_delete=models.CASCADE)
    status = models.CharField(max_length=25, choices=ORDER_STATUSES)
    deposit_balance = models.FloatField(blank=True, default=0.0, null=True)
    subtotal_after_discount = models.FloatField(blank=True, default=0.0)
    tax = models.FloatField(blank=True, default=0.0)
    current_balance = models.FloatField(blank=True, default=0.0)
    shipping = models.FloatField(blank=True, default=0.0)
    comments = models.TextField(blank=True)
    store = models.ForeignKey(
        Store, related_name='orders', on_delete=models.CASCADE)
    referral = models.CharField(
        blank=True, null=True, max_length=50, choices=REFERRAL_SOURCES)
    protection_plan = models.BooleanField(default=False, blank=True)
    financing_option = models.BooleanField(default=False, blank=True)
    delivered_date = models.DateTimeField(null=True, blank=True, default=None)
    order_type = models.CharField(
        blank=True, null=True, max_length=25, choices=ORDER_TYPES)
    bonus_elig_date = models.DateField(null=True, blank=True, default=None)
    is_quote = models.BooleanField(null=True, blank=True, default=False)

    # track change history
    audit_log = AuditLog()

    objects = OrderManager()  # customer manager

    @property
    def not_placed(self):
        # no status        'new'                 'any item, which is not in stock, and does not have po#
        # return not self.status or self.status == 'N' or any([item for item in self.orderitem_set if not
        # item.in_stock and not item.po_num])
        if self.status not in ('I', 'X', 'E', 'QUOT'):
            return any(
                [item for item in self.ordered_items.all() if item.status not in ("S", "I") and item.po_num == ''])
        return False

    @property
    def balance_due(self):
        """ Balance due after the deposits """
        if self.status == 'X' or self.is_quote:  # Quote, Dummy -- should be no balance
            return 0.0

        return round(self.grand_total - self.balance, 2)

    @property
    def balance(self):
        """ Current order balance """
        if self.status == 'X' or self.is_quote:  # Quote, Dummy -- should be no balance
            return 0.0

        total_paid = 0.0
        for payment in self.payments.all():
            total_paid += payment.amount

        return round(total_paid, 2)

    @property
    def grand_total(self):
        """ Grand Total (Subtotal + tax + shipping) """
        grand_total = self.subtotal_after_discount + self.tax + self.shipping
        return round(grand_total, 2)

    @property
    def tracking_alert(self):
        reason = set()
        month_ago = get_prev_month_date()
        for i in self.ordered_items.all():
            if not i.in_stock:
                if i.eta is None:
                    reason.add('ETA missing')
                if i.order_last_checked_date is None or i.order_last_checked_date < month_ago.date():
                    reason.add("Tracking Date not current")
        return ', '.join(reason)

    @property
    def total_profit(self):
        """ Total Profit amount (sum of price - cost for all items) """
        total_profit = 0.0
        for i in self.ordered_items.all():
            try:
                total_profit += i.price - i.cost
            except Exception:
                pass
        return round(total_profit, 2)

    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        prefix = ""
        if self.is_quote:
            prefix = "Quote - "
        return "{0}#{1}".format(prefix, self.number)

    def get_absolute_url(self):
        return reverse("order_detail", kwargs={"pk": self.pk})


class CabinetryOrder(object):
    """
    A model class representing the Kitchen/Cabinetry Order data
    """

    # objects = models.Manager()      #default
    # objects = OrderManager()  # customer manager

    # track change history
    audit_log = AuditLog()

    class Meta:
        ordering = ["-order_date"]
        db_table = "cabinetry_orders"
        permissions = (
            ("view_cabinetry_orders", "Can View Kitchen/Cabinetry Order Info"),
            ("view_cabinetry_sales", "Can View Kitchen/Cabinetry Sales Reports"),
        )

    def get_absolute_url(self):
        return reverse("cabinetry_order_detail", kwargs={"pk": self.pk})


class OrderItem(TimeStampedModel, AuthStampedModel):
    """
    A model class representing Items Ordered (stock items, special order items, etc).
    """
    class Meta:
        db_table = "order_items"
        verbose_name_plural = "ordered items"

    ITEM_STATUSES = (
        ('P', 'Unordered'),
        ('O', 'Ordered'),
        ('R', 'Received'),
        ('D', 'Delivered'),
        ('S', 'In Stock'),
        ('I', 'Historical (Excel Import)'),
    )

    ITEM_CATEGORIES = (
        ('ACCESSORIES', 'Accessories'),
        ('ACCENT_TABLES', 'Accent / Coffee / Side Tables'),
        ('APPLIANCES', 'Appliances'),
        ('APP_INSTALL', 'Appliances Installation'),
        ('ARMCHAIRS', 'Armchairs / recliners'),
        ('BACKSPLASH', 'Backsplash'),
        ('BATHROOM', 'Bathroom Cabinets'),
        ('BEDROOM', 'Bedroom beds / nightstands'),
        ('CAB_INSTALL', 'Cabinets Installation'),
        ('CABINETS', 'Cabinets'),
        ('CLOSETS', 'Closets'),
        ('COUNTER', 'Counter Tops'),
        ('DESIGN', 'Design Fee'),
        ('DINING_CHAIRS', 'Dining Chairs'),
        ('FLOORING', 'Flooring'),
        ('LIGHTING', 'Lighting'),
        ('MEDIA', 'Media Cabinets / Entertainment Units'),
        ('OFFICE', 'Office Furniture'),
        ('OUTDOOR', 'Outdoor'),
        ('PILLOWS', 'Pillows'),
        ('RUGS', 'Rugs'),
        ('SOFAS', 'Sofas / sectionals / loveseats'),
        ('TABLES', 'Tables Dining / Living'),
        ('Discount', 'Discount'),
        ('VANITIES', 'Vanities'),
        ('WALL_SYSTEMS', 'Wall Systems'),
        ('WINDOWS', 'Window Treatments'),
        ('OTHER', 'Other'),
    )

    VENDORS = (
        ('ALF_ITALIA', 'Alf Italia'),
        ('ALF_DAFRE', 'Alf DaFre'),
        ('BADEA', 'Badea'),
        ('BAUFORMAT', 'Bauformat'),
        ('BDI', 'BDI'),
        ('BONTEMPI', 'Bontempi'),
        ('CALLIGARIS', 'Calligaris'),
        ('CATTELAN_ITALIA', 'Cattelan Italia'),
        ('COSENTINO', 'Cosentino'),
        ('DCS', 'DCS'),
        ('EKORNES', 'Stressless'),
        ('ELITE_MODERN', 'Elite Modern'),
        ('ESTRO_MILANO', 'Estro Milano'),
        ('EUROFASE', 'Eurofase'),
        ('FISHER_PAYKEL', 'Fisher & Paykel'),
        ('FURNITALIA', 'Furnitalia'),
        ('GARRISON', 'Garrison'),
        ('GLOBAL_VIEWS', 'Global Views'),
        ('HUNTER_DOUGLAS', 'Hunter Douglas'),
        ('IDEA_GROUP', 'IDEA Group'),

furnidashboard/orders/views/api.py
from orders.serializers import OrderSerializer
from rest_framework import viewsets, filters, status
from rest_framework.authentication import SessionAuthentication
from rest_framework.parsers import MultiPartParser, FormParser, FileUploadParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from orders.models import OrderItem, Order
import logging

logger = logging.getLogger('furnicloud')

class OrderApiViewSet(viewsets.ModelViewSet):
    authentication_classes = (SessionAuthentication,)
    #permission_classes = (IsAuthenticated,)

    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    #filter_backends = (filters.DjangoFilterBackend,)
    #filter_class = StoreTrafficEntryFilter
    # filter_fields = ('associate__first_name', 'order__number', 'paid')'

furnidashboard/orders/views/deliveries.py
from django.views.generic import DetailView, UpdateView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from django_tables2 import SingleTableView
from orders.models import OrderDelivery
from orders.tables import DeliveriesTable
import orders.forms as order_forms
import core.utils as core_utils
from core.mixins import LoginRequiredMixin, PermissionRequiredMixin


class DeliveriesTableView(LoginRequiredMixin, SingleTableView):
    model = OrderDelivery
    table_class = DeliveriesTable
    context_table_name = 'table'
    template_name = "orders/delivery_list.html"
    paginate_by = 20
    from_date = ""
    to_date = ""

    def get_queryset(self, **kwargs):
        qs = OrderDelivery.objects.filter(~Q(delivery_type='SELF'))

        date_range = ""
        try:
            date_range = self.request.GET['date_range']
            self.from_date, self.to_date = core_utils.get_date_range_from_string(date_range, self.request)
        except KeyError as e:
            self.from_date, self.to_date = core_utils.get_date_range_from_string('week', self.request)

        lookup_kwargs = {
            '%s__gte' % 'scheduled_delivery_date': self.from_date,
            '%s__lt' % 'scheduled_delivery_date': self.to_date,
        }
        qs = qs.filter(**lookup_kwargs)

        return qs

    def get_context_data(self, **kwargs):
        context = super(DeliveriesTableView, self).get_context_data(**kwargs)

        date_range = 'month'
        if "date_range" in self.request.GET:
            context['date_range_filter'] = order_forms.DateRangeForm(self.request.GET)
        else:
            context['date_range_filter'] = order_forms.DateRangeForm(initial={'date_range': date_range})

        if self.from_date and self.to_date:
            context['dates_caption'] = "{0} - {1}".format(self.from_date.strftime("%m/%d/%Y"),
                                                          self.to_date.strftime("%m/%d/%Y"))

        return context


# -----------------------------------------------------------------------

class DeliveryDetailView(LoginRequiredMixin, DetailView):
    model = OrderDelivery
    context_object_name = "delivery"
    template_name = "orders/delivery_detail.html"


# -----------------------------------------------------------------------

class DeliveryDeleteView(LoginRequiredMixin, DeleteView):
    model = OrderDelivery
    success_url = reverse_lazy("delivery_list")


# -----------------------------------------------------------------------

class DeliveryUpdateView(LoginRequiredMixin, UpdateView):
    model = OrderDelivery
    context_object_name = "delivery"
    template_name = "orders/delivery_update.html"
    form_class = order_forms.OrderDeliveryForm

    def get_form_kwargs(self):
        kwargs = super(DeliveryUpdateView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

furnidashboard/orders/views/mixins.py
import datetime

from crispy_forms.helper import FormHelper
from django.core.exceptions import ImproperlyConfigured
from django.db.models import Q
from django.utils import timezone
from django.views.generic import ListView
from django_tables2 import RequestConfig

from core.utils import get_current_month_date_range
from orders.filters import OrderFilter
from orders.tables import OrderTable


class FilteredTableMixin(object):
    formhelper_class = FormHelper
    context_filter_name = 'filter'
    context_table_name = 'table'
    model = None
    table_class = OrderTable
    context_object_name = "order_list"
    table_paginate_by = None
    filter_class = OrderFilter
    filter_form_id = 'order-filter'
    include_cabinetry_orders = False

    def get_queryset(self, **kwargs):
        qs = super(FilteredTableMixin, self).get_queryset(**kwargs)
        qs = qs.prefetch_related('payments'). \
            select_related('store'). \
            select_related('customer'). \
            prefetch_related('commissions'). \
            prefetch_related('commissions__associate'). \
            distinct()

        self.setup_filter(queryset=qs)
        qs = self.filter.qs

        if not self.include_cabinetry_orders:
            qs = qs.exclude(order_type__in=('cabinetry', 'cabinetry_quote'))

        return qs

    def setup_filter(self, **kwargs):
        self.filter = self.filter_class(self.request.GET, queryset=kwargs['queryset'])
        # self.filter.helper = self.formhelper_class()
        self.filter.helper.form_id = self.filter_form_id
        # self.filter.helper.form_class = "blueForms, well"
        self.filter.helper.form_method = "get"
        # self.filter.helper.add_input(Submit('submit', 'Submit'))

    def get_table(self, **kwargs):
        try:
            page = self.kwargs['page']
        except KeyError:
            page = 1
        options = {'paginate': {'page': page, 'per_page': self.table_paginate_by}}
        table_class = self.table_class
        table = table_class(**kwargs)
        RequestConfig(self.request, **options).configure(table)
        return table

    def get_context_data(self, **kwargs):
        context = super(FilteredTableMixin, self).get_context_data(**kwargs)
        table = self.get_table(data=context[self.context_object_name])
        context[self.context_table_name] = table
        context[self.context_filter_name] = self.filter
        return context

furnidashboard/templates/orders/form.html
{% extends "base.html" %}

{% block title %}Modify Order{% endblock %}

{% block page_title %}Modify Order {{order}}{% endblock page_title %}

{% block extra_js %}
  {{ form.media }}
{% endblock %}

{% block content %}

<form action="" method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }} 

  {{ form.as_p }}
  
  <input type="submit" value="Save"/>

</form>

{% endblock content %}

furnidashboard/templates/orders/non_furniture_orders_list.html
{% extends "base.html" %}

{% load static %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

{% block title %}Kitchen/Cabinetry Orders for {{ month|date:'b, Y'}} {% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                $("#orderMonthsRangeForm").on('submit', function (e) {
                    e.preventDefault();
                    var year = $(this).find('select[name="year"]').val();
                    var month = $(this).find('select[name="month"]').val();
                    var pathNameArr =  window.location.pathname.split("/");
                    window.location = "/" + pathNameArr[1] + "/" + pathNameArr[2] + "/" + year + "/" + month;
                });
            });
        });
    </script>
{% endblock %}

{% block page_title %}{{ title }} | {{ month|date:'F, Y'}} {% endblock page_title %}

{% block content %}


    {% if perms.orders.add_order %}
        <aside id="createOrderAside">
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                New Order
            </button>
        </aside>
    {% endif %}

    <div id="order-list" class="monthly-orders">

        <form name="order-date-range" id="orderMonthsRangeForm" class="form" style="margin-bottom:10px">
            <select name="year">
                {% for y in years_list %}
                    <option value="{{ y }}" {% if current_year == y %}selected="selected"{% endif %}
                            class="form-control">{{ y }}</option>
                {% endfor %}
            </select>

            <select name="month">
                {% for m in months_list %}
                    <option value="{{ m.0 }}" {% if current_month == m.0 %}selected{% endif %}
                            class="form-control">{{ m.1 }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Submit" class=""/>
        </form>

        <!-- Filter Form -->
        {% crispy filter.form filter.helper %}

        {% render_table table %}

    </div>

    {% include "partial/_order_create_modal.html" %}


{% endblock %}

furnidashboard/templates/orders/order_archive_month.html
{% extends "base.html" %}

{% load static %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

{% block title %}Orders for {{ month|date:'b, Y'}} {% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                $("#orderMonthsRangeForm").on('submit', function (e) {
                    e.preventDefault();
                    var year = $(this).find('select[name="year"]').val();
                    var month = $(this).find('select[name="month"]').val();
                    // console.log('y ' + year);
                    // console.log('m ' + month);
                    window.location = "/orders/" + year + "/" + month;
                });
            });
        });
    </script>
{% endblock %}

{% block page_title %}{{ month|date:'F, Y'}} {% endblock page_title %}

{% block content %}


    {% if perms.orders.add_order %}
        <aside id="createOrderAside">
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                New Order
            </button>
        </aside>
    {% endif %}

    <div id="order-list" class="monthly-orders">

        <form name="order-date-range" id="orderMonthsRangeForm" class="form" style="margin-bottom:10px">
            <select name="year">
                {% for y in years_list %}
                    <option value="{{ y }}" {% if current_year == y %}selected="selected"{% endif %}
                            class="form-control">{{ y }}</option>
                {% endfor %}
            </select>

            <select name="month">
                {% for m in months_list %}
                    <option value="{{ m.0 }}" {% if current_month == m.0 %}selected{% endif %}
                            class="form-control">{{ m.1 }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Submit" class=""/>
        </form>


        <!-- Filter Form -->
        {% crispy filter.form filter.helper %}

        {% render_table table %}

    </div>

    <section id="totals" class="clearfix">
        <div id="totals-month">
            <h4>Month Sales Totals</h4>
            {% render_table month_totals_table %}
        </div>

        <div id="orders-ytd-totals">
            <h4>YTD Sales Totals (Jan - {{ month|date:'b'|capfirst }}, {{ current_year }})</h4>
            {% render_table ytd_totals_table %}
        </div>
        <br/><br/>
        <div id="totals-assoc">
            <h4>{{ month|date:'F, Y' }} Standings</h4>
            {% render_table sales_by_associate %}
        </div>
    </section>

    {% include "partial/_order_create_modal.html" %}

{% endblock %}

furnidashboard/templates/orders/order_history.html
{% extends "base.html" %}

{% load extras %}

{% block title %}Order #{{ object.number }} History{% endblock %}

{% block page_title %}<p class=text-center">Order #{{ order.number }} History</p>{% endblock page_title %}

{% block content %}

    <div class="well hidden-print">
        <a href="{% url 'order_detail' object.pk %}" class="btn btn-default" title="View Order">Order Detail</a>
        {% if perms.orders.change_order %}
            <a href="{% url 'order_edit' object.pk %}" class="btn btn-default" title="Edit Order">Edit Order</a>
        {% endif %}
    </div>
    <hr/>
    <h3>Order Update History</h3>
    <table id="order-audit-log-table-exp" class="table table-bordered">
        <thead>
            <th>Action</th>
            <th>Action Date</th>
            <th>User</th>
            <th>Order #</th>
            <th>Order Date</th>
            <th>Status</th>
            <th>Store</th>
            <th>Customer</th>
            <th>Subtotal</th>
            <th>Tax</th>
            <th>Shipping</th>
            <th>Protection Plan</th>
            <th>Financing Plan</th>
            <th>Delivered Date</th>
            <th>Bonus Elig Date</th>
            <th>Comments</th>
        </thead>
        <tbody>
        {% for entry in audit_log_objects %}
            <tr class="zebra">
                <td>{{ entry.action }}</td>
                <td>{{ entry.action_date |date:'j F, Y H:i'  }}</td>
                <td>{{ entry.action_user }}</td>
                <td>{{ entry.data.number }}</td>
                <td>{{ entry.data.order_date |date:'j F, Y'  }}</td>
                <td>{{ entry.data.get_status_display }}</td>
                <td>{{ entry.data.store }}</td>
                <td>{{ entry.data.customer }}</td>
                <td>{{ entry.data.subtotal_after_discount }}</td>
                <td>{{ entry.data.tax }}</td>
                <td>{{ entry.data.shipping }}</td>
                <td>{{ entry.data.protection_plan|yesno }}</td>
                <td>{{ entry.data.financing_option|yesno }}</td>
                <td>{{ entry.data.delivered_date |date:'m/d/Y'  }}</td>
                <td>{{ entry.data.bonus_elig_date |date:'m/d/Y'  }}</td>
                <td>{{ entry.data.comments }}</td>

                {% comment %}
                {% for field in entry.data.items %}
                    <td>{{ field.0 }} | {{ field.1 }} </td>
                {% endfor %}
                {% endcomment %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <hr/>

    <h3>Item Update History</h3>
    <table id="order-item-history-log-table" class="table table-bordered">
        <thead>
            <th>Item #</th>
            <th>Action</th>
            <th>Date</th>
            <th>User</th>
            <th>Item Description</th>
            <th>Item Status</th>
            <th>Item In Stock</th>
            <th>PO #</th>
            <th>PO Date</th>
            <th>Ack #</th>
            <th>Ack Date</th>
            <th>ETA</th>
        </thead>
        <tbody>
        {% for entry in item_history %}
            <tr>
                <td>{{ entry.no }}</td>
                <td>{{ entry.data.get_action_type_display }}</td>
                <td>{{ entry.data.action_date |date:'j F, Y H:i'  }}</td>
                <td>{{ entry.data.action_user }}</td>
                <td>{{ entry.data.description }}</td>
                <td>{{ entry.data.get_status_display }}</td>
                <td>{{ entry.data.in_stock|yesno }}</td>
                <td>{{ entry.data.po_num|default_if_none:"" }}</td>
                <td>{{ entry.data.po_date|date:'j F, Y' |default_if_none:"" }}</td>
                <td>{{ entry.data.ack_num |default_if_none:"" }}</td>
                <td>{{ entry.data.ack_date|date:'j F, Y' |default_if_none:"" }}</td>
                <td>{{ entry.data.eta|default_if_none:"" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <hr/>

    <h3>Payment Update History</h3>
    <table id="order-payment-history-log-table" class="table table-bordered">
        <thead>
            <th>Payment #</th>
            <th>Action</th>
            <th>Date</th>
            <th>User</th>
            <th>Payment Date</th>
            <th>Payment Type</th>
            <th>Amount</th>
            <th>Comments</th>
        </thead>
        <tbody>
        {% for entry in payment_history %}
            <tr>
                <td>{{ entry.no }}</td>
                <td>{{ entry.data.get_action_type_display }}</td>
                <td>{{ entry.data.action_date|date:'j F, Y H:i'  }}</td>
                <td>{{ entry.data.action_user }}</td>
                <td>{{ entry.data.payment_date|date:'j F, Y'  }}</td>
                <td>{{ entry.data.get_payment_type_display }}</td>
                <td>{{ entry.data.amount }}</td>
                <td>{{ entry.data.comments|default_if_none:"" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h3>Commissions Update History</h3>
    <table id="order-commission-history-log-table" class="table table-bordered">
        <thead>
            <th>Commission #</th>
            <th>Action</th>
            <th>Date</th>
            <th>User</th>
            <th>Associate</th>
            <th>Status</th>
            <th>Amount</th>
            <th>Paid Date</th>
            <th>Comments</th>
        </thead>
        <tbody>
        {% for entry in commission_history %}
            <tr>
                <td>{{ entry.no }}</td>
                <td>{{ entry.data.get_action_type_display }}</td>
                <td>{{ entry.data.action_date|date:'j F, Y H:i'  }}</td>
                <td>{{ entry.data.action_user }}</td>
                <td>{{ entry.data.associate }}</td>
                <td>{{ entry.data.get_status_display }}</td>
                <td>{{ entry.data.amount }}</td>
                <td>{{ entry.data.paid_date|date:'j F, Y'  | default_if_none:"" }}</td>
                <td>{{ entry.data.comments|default_if_none:"" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}