furnidashboard/datetimepicker/urls.py
from django.conf.urls import url

from .views import JSTemplateView


urlpatterns = [url(r'^loader.js',
               JSTemplateView.as_view(),
               name='datetimepicker-loader')]

furnidashboard/commissions/models.py
from audit_log.models.managers import AuditLog
from django.db.models import Q
from django.db import models
from django.conf import settings
from django_extensions.db.models import TimeStampedModel
from audit_log.models import AuthStampedModel

import orders
from orders.models import Order
import logging


logger = logging.getLogger('furnicloud')


class CommissionManager(models.Manager):

    def regular(self):
        return self.get_queryset()\
            .filter(manager_commission_flag=False)\
            .select_related('order')\
            .filter(~Q(order__order_type__in=('cabinetry', 'cabinetry_quote')))

    def active(self):
        return self.regular()\
            .select_related('order')\
            .filter(order__status__in=orders.models.Order.ORDER_ACTIVE_STATUSES)

    def all_commissions(self):
        return super(CommissionManager, self).get_queryset()


class Commission(TimeStampedModel, AuthStampedModel):
    COMMISSION_STATUES = (
        ('NEW', 'Unclaimed'),
        ('PENDING', 'Claimed'),
        ('INELIGIBLE', 'Ineligible/Rejected'),
        ('PAID', 'Paid'),
    )

    associate = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, null=True, blank=True,
                                  related_name='order_commissions', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, related_name='commissions', on_delete=models.CASCADE)
    paid = models.BooleanField(default=False, blank=True)
    status = models.CharField(max_length=50, choices=COMMISSION_STATUES, default='NEW')
    amount = models.FloatField(blank=True, default=0.0)
    paid_date = models.DateTimeField(null=True, blank=True)
    comments = models.TextField(blank=True)
    manager_commission_flag = models.BooleanField(default=False, blank=True)
    portion_percentage = models.FloatField()

    def __str__(self):
        s = 'Commission: pk={0}, amount={1}, orderId={2}'.format(self.pk, self.amount, self.order_id)
        return s

    def __unicode__(self):
        return str(self)

    # track change history
    audit_log = AuditLog()

    objects = CommissionManager()

    @property
    def sale_portion(self):
        sales_amount = self.order.subtotal_after_discount * self.portion_percentage / 100.0
        return sales_amount

    @property
    def is_eligible_for_claim(self):
        """
        order is eligible for claim if
        - order is delivered or closed OR
        - order has in stock items and at least 1 delivery was entered
        """

        if self.order.status in ('D', 'C'):
            return True

        # get ordered items list
        # order_items = self.order.ordered_items.all()
        # # check if there is any "In Stock" item
        # if len(order_items) > 1 and any([i for i in order_items if i.status == 'S']):
        #     # check if Delivery has been entered for order
        #     if self.order.orderdelivery_set.count() > 0:
        #         return True

        return False

    class Meta:
        db_table = "commissions"
        permissions = (
            ("update_commissions_payment", "Can Update Commission Payment Information"),
            ("view_commissions", "View all commissions"),
            ("edit_commissions", "Change Commissions"),
        )


# @receiver(models.signals.post_save, sender=Order)
# def execute_after_save(sender, instance, created, *args, **kwargs):
#     manager = com_utils.get_manager_account()
#     com_amount = instance.subtotal_after_discount * 0.01
#
#     dt = datetime.strptime('2018-01-01', '%Y-%m-%d')
#     dt = timezone.make_aware(dt, timezone.get_current_timezone())
#     if instance.order_date >= dt:
#         if created or len(com_utils.get_manager_commission_for_order(instance)) == 0:
#             # upon order creation, need to create a commission for manager
#             logger.debug('Creating a manager commission for order ' + str(instance))
#             c = Commission.objects.create(order=instance, status='NEW', associate=manager,
#                                           manager_commission_flag=True,
#                                           amount=com_amount)
#             c.save()
#         else:
#             # when order is saved, update the manager's commission amount
#             logger.debug('Updating manager\'s commission for order %s' % instance)
#             c = Commission.objects.all().filter(order=instance, manager_commission_flag=True, associate=manager)
#             for cur_com in c:
#                 cur_com.amount = com_amount
#                 cur_com.save()
#
#
# @receiver(models.signals.pre_delete, sender=Commission)
# def execute_pre_delete(sender, instance, *args, **kwargs):
#     logger.debug("Commission Pre Delete")
#     instance.audit_log.disable_tracking()
#
#
# @receiver(models.signals.post_save, sender=Commission)
# def execute_after_com_save(sender, instance, created, *args, **kwargs):
#     if instance.manager_commission_flag:
#         return
#
#     manager = com_utils.get_manager_account()
#     com_amount = instance.order.subtotal_after_discount * 0.01
#
#     dt = datetime.strptime('2018-01-01', '%Y-%m-%d')
#     dt = timezone.make_aware(dt, timezone.get_current_timezone())
#     if instance.order.order_date >= dt:
#         if not created and \
#                 len([com for com in com_utils.get_commissions_for_order(instance.order) if com.status == 'NEW']) == 0:
#             # when order is saved, update the manager's commission amount
#             logger.debug('Updating manager\'s commission for order %s' % instance.order)
#             c = Commission.objects.all().filter(order=instance.order, manager_commission_flag=True, associate=manager)
#             for cur_com in c:
#                 cur_com.amount = com_amount
#                 cur_com.status = 'PENDING'
#                 cur_com.save()

furnidashboard/commissions/views.py
import logging
import logging
import sys
from collections import OrderedDict
from datetime import datetime, timedelta

import django.forms as forms
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.db.models.aggregates import Sum
from django.db.models.functions import TruncMonth
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.views.generic import ListView, UpdateView, TemplateView, DetailView
from django_tables2 import RequestConfig

import commissions.forms as commission_forms
import commissions.utils as commission_utils
import core.forms as core_forms
import core.utils as core_utils
import orders.utils as order_utils
from commissions.filters import CommissionListFilter, CommissionPaymentHistoryFilter
from core.mixins import PermissionRequiredMixin
from orders.models import Order
from orders.tables import SalesByAssociateWithBonusTable, CommissionsTable, SalesByAssocSalesTable, \
    ProtectionPlanBonusTable, ProtectionPlanByAssociateDetailsTable
from .models import Commission

logger = logging.getLogger('furnicloud')


class CommissionsList(PermissionRequiredMixin, TemplateView):
    model = Commission
    template_name = "commissions/commissions_list.html"
    cutoff_dt = datetime(2017, 5, 1)  # last 6 months
    cutoff_dt = timezone.make_aware(cutoff_dt, timezone.get_current_timezone())
    context_filter_name = 'filter'
    filter_class = CommissionListFilter
    filter_form_id = 'commissions-filter'

    required_permissions = (
        'commissions.view_commissions',
    )

    def get_queryset(self):
        qs = Commission.objects.all()
        qs = qs \
            .select_related('order') \
            .select_related('associate') \
            .prefetch_related('order__customer') \
            .prefetch_related('order__ordered_items') \
            .prefetch_related('order__payments') \
            .prefetch_related('order__orderdelivery_set') \
            .prefetch_related('order__commissions') \
            .filter(~Q(order__status__in=('QUOT', 'X', 'I', 'E'))) \
            .filter(~Q(order__order_type__in=('cabinetry', 'cabinetry_quote'))) \
            .distinct()

        # .filter(order__order_date__gt=self.cutoff_dt)
        self.setup_filter(queryset=qs)
        return self.filter.qs

    def setup_filter(self, **kwargs):
        # Create a mutable QueryDict object, default is immutable
        initial = QueryDict(mutable=True)
        initial['order_date_from'] = core_utils.get_date_n_months_ago(36)
        initial['order_date_to'] = core_utils.get_month_last_day()

        # if no filters are present, try to get filters stored in session

        initial.update(self.request.GET)
        if 'order_date_from' not in self.request.GET:
            # restore filters from session
            initial.update(self.request.session.get('commission_filters', QueryDict()))

        self.filter = self.filter_class(initial, queryset=kwargs['queryset'])

        # save selected filters to session if Filter button was pressed
        if 'order_date_from' in self.request.GET:
            self.request.session['commission_filters'] = self.filter.data

        self.filter.helper.form_id = self.filter_form_id
        self.filter.helper.form_method = "get"

    def get_context_data(self, **kwargs):
        context = super(CommissionsList, self).get_context_data(**kwargs)

        is_manager = self.request.user.groups.filter(Q(name="managers")).exists()
        commissions_data = []
        commission_subtotals = {}

        for c in self.get_queryset():
            order = c.order
            sales_amount = c.sale_portion
            if c.manager_commission_flag:
                # manager commission applies to whole order, not partial
                sales_amount = order.subtotal_after_discount

            associate = c.associate.first_name

            claim_action = 'Ineligible (check order)'
            if c.status in ('PAID', 'INELIGIBLE') and not is_manager:
                claim_action = ''
            elif c.status in ('PENDING', 'INELIGIBLE') or is_manager:
                claim_action = reverse("commission_edit", kwargs={"pk": c.pk})
                claim_action = mark_safe('<a href="{0}" class="button">{1}</a>'.format(claim_action, 'Edit'))
            elif c.is_eligible_for_claim:
                if c.associate == self.request.user or self.request.user.username == 'admin':
                    claim_action = reverse("commission_claim", kwargs={"pk": c.pk})
                    claim_action = mark_safe('<a href="{0}" class="button">{1}</a>'.format(claim_action, 'Claim'))
                else:
                    claim_action = 'To be claimed by %s' % associate

            commission_status = c.get_status_display().upper()
            if c.status == 'NEW':
                commission_status = 'UNCLAIMED'

            cur_commission = {
                'order': order,
                'order_date': order.order_date,  # .strftime(settings.DATE_FORMAT_STANDARD),
                'delivered_date': order.delivered_date,
                'order_status': order.get_status_display(),
                'order_subtotal': order.subtotal_after_discount,
                'sale_portion': sales_amount,
                'order_grandtotal': order.grand_total,
                'order_balance_due': order.balance_due,
                'associate': associate,
                # 'estimated_amount': c.amount,
                'amount': c.amount,
                'paid_date': c.paid_date,
                # 'commission_pk': c.pk,
                'commission_status': commission_status,
                'claim_action': claim_action,
                'customer': order.customer,
                'manager_commission_flag': c.manager_commission_flag,
            }
            commissions_data.append(cur_commission)

            # create table for commission subtotals by associate
            if not associate in commission_subtotals:
                commission_subtotals[associate] = {'PENDING': 0.0,
                                                   'PAID': 0.0,
                                                   'INELIGIBLE': 0.0,
                                                   'NEW': 0.0,
                                                   'SALES_SUBTOTAL': 0.0,
                                                   'ESTIMATED_COMMISSIONS': 0.0}

            if c.status.lower() == 'pending' or c.status.lower() == 'paid' or c.manager_commission_flag:
                commission_subtotals[associate][c.status] += c.amount
                commission_subtotals[associate]['SALES_SUBTOTAL'] += sales_amount
                estimated_commission = sales_amount * settings.COMMISSION_PERCENT
                if c.associate.username in 'greg':
                    if c.manager_commission_flag:
                        estimated_commission = order.subtotal_after_discount * 0.01
                    else:
                        estimated_commission = 0.0
                commission_subtotals[associate]['ESTIMATED_COMMISSIONS'] += estimated_commission

        commissions_table = CommissionsTable(commissions_data)
        RequestConfig(self.request).configure(commissions_table)
        context['table'] = commissions_table

        commission_subtotals = OrderedDict(
            sorted(commission_subtotals.items(), key=lambda row: row[1]['SALES_SUBTOTAL']))
        context['subtotals_table'] = commission_subtotals

        context['title'] = 'Commissions'
        context['message'] = '* \'Dummy\' and \'Quotation\' orders are excluded from this list'
        context[self.context_filter_name] = self.filter

        return context


class ManagerCommissionsList(CommissionsList):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.username in ('greg', 'dmitriy', 'admin'):
            redirect(reverse('login'))


class CommissionPaymentHistoryView(PermissionRequiredMixin, TemplateView):
    model = Commission
    template_name = "commissions/commissions_list.html"
    context_filter_name = 'filter'
    filter_class = CommissionPaymentHistoryFilter
    filter_form_id = 'commissions-filter'

    required_permissions = (
        'commissions.view_commissions',
    )

    def get_queryset(self):

        qs = Commission.objects.regular()

        # if self.request and (self.request.user.username in ('greg', 'admin', 'dmitriy')):
        #    qs = Commission.objects.all()

        qs = qs \
            .select_related('order') \
            .select_related('associate') \
            .prefetch_related('order__customer') \
            .prefetch_related('order__ordered_items') \
            .prefetch_related('order__payments') \
            .prefetch_related('order__orderdelivery_set') \
            .prefetch_related('order__commissions') \
            .filter(status='PAID') \
            .filter(~Q(order__status__in=('QUOT', 'X', 'I'))) \
            .filter(~Q(order__order_type__in=('cabinetry', 'cabinetry_quote'))) \
            # .filter(order__order_date__gt=self.cutoff_dt)

        self.setup_filter(queryset=qs)
        return self.filter.qs

    def setup_filter(self, **kwargs):
        # Create a mutable QueryDict object, default is immutable
        initial = QueryDict(mutable=True)
        from_date, to_date = core_utils.get_current_month_date_range()

        from_date = datetime.combine(from_date, datetime.min.time())
        to_date = datetime.combine(to_date, datetime.min.time())

        initial['commissions_paid_date_from'] = core_utils.date_with_tz(from_date)
        initial['commissions_paid_date_to'] = core_utils.date_with_tz(to_date)

        # if no filters are present, try to get filters stored in session
        # if self.request.GET.get('submit', '') != u'Filter':

furnidashboard/templates/commissions/commission_detail.html
{% extends "base.html" %}

{% load extras %}

{% block title %} {{ commission.associate.first_name }}'s commission for #{{commission.order.number}} {% endblock %}

{% block actions %}
<div class="well hidden-print">
    {% if perms.commissions.edit_commissions %}
    <a href="{% url 'commission_edit' commission.pk %}" title="Edit Claim">
        <span class="glyphicon glyphicon-pencil"></span>&nbsp;Update Commission</a>
    {% endif %}
</div>
{% endblock %}

{% block page_title %}
{{ commission.associate.first_name }}'s commission for #{{commission.order.number}}
{% endblock page_title %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-md-3">
            <table class="table">
                <tr>
                    <td class="cell-label">Order</td>
                    <td class="cell-value">{{ commission.order.number }}</td>
                </tr>
                <tr>
                    <td class="cell-label">Order Date</td>
                    <td class="cell-value">{{ commission.order.order_date|date:'j F, Y' }}</td>
                </tr>
            </table>
        </div>
        <!--<div class="col-md-2">
            <h4>Order:</h4>
            {{ commission.order.number }}
        </div>
        <div class="col-md-2">
            <h4>Order Date:</h4>
            {{ commission.order.order_date|date:'j F, Y' }}
        </div>-->
        <div class="col-md-2 col-md-offset-1">
            <h4>Associate:</h4>
            <strong>{{ commission.associate.first_name}}</strong>
        </div>
        <div class="col-md-2">
            <h4>Amount Claimed:</h4>
            {{ commission.amount|dollars }}
        </div>
        <div class="col-md-2">
            <h4>Status:</h4>
            {{ commission.get_status_display }}
        </div>
        <div class="col-md-2">
            <h4>Paid Date:</h4>
            {{ commission.paid_date|date:'j F, Y' }}
        </div>

    </div>
</div>

<h3>Comments</h3>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <p>{{commission.comments}}</p>
            </div>
        </div>
    </div>
</div>

<hr/>

<h3>#{{ commission.order.number }} Order Summary</h3>

{% include "partial/_commission_order_summary.html" %}


<hr/>

<div class="row pull-right">
    <h4>Audit Trail:</h4>
    <table id="order-audit-trail" class="table">
        <tr>
            <td>Created:</td>
            <td> {{ commission.created|date:'j F, Y H:i' }}</td>
            <td>by:</td>
            <td>{{ commission.created_by }}</td>
        </tr>
        <tr>
            <td>Modified:</td>
            <td>{{ commission.modified|date:'j F, Y H:i' }}</td>
            <td>by:</td>
            <td> {{ commission.modified_by }}</td>
        </tr>
    </table>
</div>

{% endblock content %}

furnidashboard/templates/commissions/commission_update.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load static %}
{% load extras %}

{% block title %}
    {% if page_title %}
        {{ page_title }}
    {% else %}
        Commission for order #{{ commission.order.number }}
    {% endif %}
{% endblock %}

{% block page_title %}
    {% if commission.pk %}
        {% ifequal action 'claim_action' %}
            Claim Commissions | #{{ commission.order.number }}
        {% else %}
            Update Commission | #{{ commission.order.number }}
        {% endifequal %}
    {% else %}
        Create Commission
    {% endif %}

    {% if commission.manager_commission_flag %}
        <h3 style="text-align: center">Manager's Commission</h3>
    {% endif %}

{% endblock page_title %}

{% block extra_js %}
    {{ form.media }}
    <script>
        var warningMsg = $("<div>Auto-populated. Check amount!</div>");
        warningMsg.css({
            "color": "#a50c0c",
            "font-weight": "bold",
            "margin": ".3em 0 0 0"
        });
        $(document).ready(function() {
            $("input.form-control.autopopulated").parents(".form-group").append(warningMsg);

            var d = new Date();
            var datestring = (d.getMonth()+1).toString().padStart(2, '0')  + "/" + d.getDate().toString().padStart(2, '0') + "/" + d.getFullYear();

            $status = $("#id_status");
            $paid = $("#id_paid");
            $paid_date = $("#id_paid_date");

            if ($status.val().trim() !== "PAID") {
                $paid.removeAttr("checked");
            } else {
                $paid.prop("checked", "checked");
            }

            $status.change(function() {
                if ($status.val().trim() !== "PAID") {
                    $paid.removeAttr("checked");
                    $paid_date.val("");
                } else {
                    $paid.prop("checked", "checked");
                    if ($paid_date.val().trim() === "") {
                        $paid_date.val(datestring);
                    }
                }
            });
            $paid.change(function() {
                if ($paid.prop("checked") && $status.val() !== 'PAID') {
                    $status.val('PAID');
                    if ($paid_date.val().trim() === "") {
                        $paid_date.val(datestring);
                    }
                }
                if (!$paid.prop("checked") && $status.val() === 'PAID') {
                    $status.val("PENDING");
                    $paid_date.val("");

                }
            });


        });
    </script>
{% endblock extra_js %}

{% block extra_css %}
    <style type="text/css">
        .delete-row {
            margin-left: 5px;
        }
    </style>
{% endblock %}

{% block content %}

    <form action="" method="POST" enctype="multipart/form-data" id="orderForm" role="form" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.management_form }}
        {% bootstrap_form_errors form %}

        <fieldset>
{#            <legend>Commssion Details</legend>#}
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <h3><i>Associate:</i> {{ commission.associate.first_name }} {{ commission.associate.last_name }}</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="row">
                                <div class="col-md-8">
                                    {% bootstrap_field form.amount addon_before='$' show_label=False  %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-7">

                                    <span style="font-size:1em; font-weight:bold">
                                    {% if not commission.manager_commission_flag %}
                                        *2.5% of Order Subtotal <br/>
                                        <i>Estimated amount:</i> ${{ estimated_commission }}
                                    {% else %}
                                        *1% of Order Subtotal
                                    {% endif %}
                                    </span>

                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 well">
                            {% ifequal action 'edit_action' %}
                                <h4>Status</h4>
                                <div class="row">
                                    <div class="col-md-5">
                                        {% bootstrap_field form.associate %}
                                        {% bootstrap_field form.status %}
                                    </div>
                                    <div class="col-md-3">
                                        {% bootstrap_field form.paid %}
                                    </div>

                                </div>

                                <div class="row">
                                    <!-- <div class="col-md-5 text-right" style="padding-top:1.5em" >

                                    </div> -->
                                    <div class="col-md-5">
                                        {% bootstrap_field form.paid_date  %}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        {% bootstrap_field form.comments  %}
                                    </div>
                                </div>

                            {% else %}
                                {% bootstrap_field form.status %}
                            {% endifequal %}


                        </div>

                    </div>

                    <br/>

                    <div class="row">
                        <div class="col-md-3">
                            {% ifequal action 'claim_action' %}
                                <input type="submit" id="submitButton" class="btn btn-primary btn-lg" value="Claim"/>
                            {% else %}
                                <input type="submit" id="submitButton" class="btn btn-primary btn-lg" value="Save"/>
                            {% endifequal %}
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>


    </form>

    <fieldset>
        <legend>Order Details</legend>
        {% include "partial/_commission_order_summary.html" %}

    </fieldset>


    <br/><br/>



{% endblock content %}

furnidashboard/templates/commissions/commissions-v2.html
{% extends "base.html" %}

{% load static %}
{% load bootstrap3 %}
{% load cache_bust %}

{% block title %}Commissions Approval{% endblock title %}

{% block page_title %}Commissions Approval{% endblock page_title %}

{% block extra_js %}

    <script src="{% static 'js/iframeResizer.min.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                iFrameResize({
                    {#log:true,#}
                    checkOrigin:false
                });

            });
        });
    </script>

{% endblock %}

{% block content %}
    {% url 'commissions_list' as commissions_list_url %}
    {% url 'commissions_paid' as commissions_paid_url %}
    {% url 'commissions_list_v2' as commissions_list_v2_url %}
    <ul class="nav nav-tabs" xmlns="http://www.w3.org/1999/html">
        <li class="{% ifequal request.path commissions_list_url %}active{% endifequal %}">
            <a href="{{ commissions_list_url }}">Commissions</a>
        </li>
        <li class="{% ifequal request.path commissions_paid_url %}active{% endifequal %}">
            <a href="{{ commissions_paid_url }}">Payment History</a>
        </li>
        {% if perms.commissions.update_commissions_payment %}
            <li class="{% ifequal request.path commissions_list_v2_url %}active{% endifequal %}">
                <a href="{{ commissions_list_v2_url }}">Quick Approval</a>
            </li>
        {% endif %}
    </ul>

    <br/>
    <style>iframe{width: 1px;min-width: 100%;position: absolute; left:0}</style>
    {% if COMMISSIONS_URL %}
        <iframe
            src="{{ COMMISSIONS_URL }}?{% cache_bust %}"
            class="iframe"
            scrolling="no"
            marginheight="0"
            frameborder="0"
            style="">
        </iframe>
    {% endif %}

{% endblock content %}

furnidashboard/templates/commissions/commissions_report.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
{% endblock %}

{% block title %}Unpaid Commissions{% endblock %}

{% block page_title %}Unpaid Commissions Report{% endblock page_title %}

{% block header_bottom %}
    <ul class="nav nav-pills" xmlns="http://www.w3.org/1999/html">
        <li>
            <a href="{% url 'sales_standings_cur' %}">Sales Report</a>
        </li>
        <li>
            <a href="{% url 'bonus_report' %}">Bonus Report</a>
        </li>
        <li class="active">
            <a href="{% url 'commissions_list' %}">Unpaid Commissions</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    {#    {{ block.super }}#}

    <div id="order-list" class="monthly-orders">

        {% if message %}
            <h4>{{ message }}</h4>
        {% endif %}

        {% render_table table %}

        <div class="panel panel-def ault">
            <div class="panel-h eading">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse"
                       href="#collapseLegend" aria-expanded="false"
                       aria-controls="collapseLegend" style="border-bottom: 1px dotted;font-size:0.8em">
                        Show column legend
                    </a>
                </h4>
            </div>
            <div id="collapseLegend" class="panel-collapse collapse "
                 role="tabpanel">
                <div class="panel-body">
                    <table class="table table-bordered" style="width:60em">
                        <tr>
                            <td>Grand Total</td>
                            <td>Subtotal After Discount + Shipping + Tax</td>
                        </tr>
                        <tr>
                            <td>Balance Due</td>
                            <td>Order Unpaid Balance (Grand Total - Total Payments)</td>
                        </tr>
                        <tr>
                            <td>Sale Portion</td>
                            <td>Associate's portion of the sale (Order Subtotal divided by # of commissions for order)
                            </td>
                        </tr>
                        <tr>
                            <td>Eligible Amount</td>
                            <td>Amount that is eligible for commissions at this
                                time. (Order is NOT eligible for commissions unless there are any customer payments
                                entered.)
                            </td>
                        </tr>
                        <tr>
                            <td>Current Commissions Due</td>
                            <td>For "Delivered" or "Closed" orders only: the commissions amount that is due
                                to be paid to the associate
                            </td>
                        </tr>
                        <tr>
                            <td>Paid Amount</td>
                            <td>Commissions already paid for an order</td>
                        </tr>
                        <tr>
                            <td>Future Commissions</td>
                            <td>For open orders: commissions amount that can be claimed after order status
                                changes to "Delivered" or "Closed"
                            </td>
                        </tr>

                    </table>
                </div>
            </div>
        </div>


    </div>
{% endblock %}