furnidashboard/datetimepicker/urls.py
from django.conf.urls import url

from .views import JSTemplateView


urlpatterns = [url(r'^loader.js',
               JSTemplateView.as_view(),
               name='datetimepicker-loader')]

furnidashboard/customers/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
import os


class Customer(models.Model):
    """
    A model class representing customer information
    """

    first_name = models.CharField(max_length=200, blank=False)
    last_name = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=30, blank=True, null=True, verbose_name="Home Phone #")
    email = models.EmailField(blank=True, null=True)
    shipping_address = models.TextField(blank=True, null=True, verbose_name="Full Shipping Address")
    billing_address = models.TextField(blank=True, null=True, verbose_name="Full Billing Address")

    company = models.CharField(max_length=100, blank=True, null=True, verbose_name="Company Name")
    mobile = models.CharField(max_length=30, blank=True, null=True, verbose_name="Mobile Phone #")

    # bill to address
    bill_addr_str = models.CharField(max_length=100, blank=True, null=True, verbose_name="Billing Address 1")
    bill_addr_str2 = models.CharField(max_length=100, blank=True, null=True, verbose_name="Billing Address 2")
    bill_addr_city = models.CharField(max_length=50, blank=True, null=True, verbose_name="Bill To City")
    bill_addr_state = models.CharField(max_length=30, blank=True, null=True, verbose_name="Bill To State")
    bill_addr_zip = models.CharField(max_length=10, blank=True, null=True, verbose_name="Bill To ZIP")

    # ship to address
    ship_addr_str = models.CharField(max_length=100, blank=True, null=True, verbose_name="Shipping Address 1")
    ship_addr_str2 = models.CharField(max_length=100, blank=True, null=True, verbose_name="Shipping Address 2")
    ship_addr_city = models.CharField(max_length=50, blank=True, null=True, verbose_name="Ship To City")
    ship_addr_state = models.CharField(max_length=30, blank=True, null=True, verbose_name="Ship To State")
    ship_addr_zip = models.CharField(max_length=10, blank=True, null=True, verbose_name="Ship To ZIP")

    notes = models.TextField(blank=True, null=True, verbose_name="Customer Notes")

    tags = TaggableManager(blank=True)

    # override model save method
    def save(self, *args, **kwargs):
        self.update_billing_address()
        self.update_shipping_address()
        super().save(*args, **kwargs)

    def update_billing_address(self):
        self.billing_address = format_full_address(self.bill_addr_str, self.bill_addr_str2, self.bill_addr_city,
                                                   self.bill_addr_state, self.bill_addr_zip)

    def update_shipping_address(self):
        self.shipping_address = format_full_address(self.ship_addr_str, self.ship_addr_str2, self.ship_addr_city,
                                                    self.ship_addr_state, self.ship_addr_zip)

    @property
    def full_name(self):
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        return reverse('customer_detail', kwargs={"pk": self.pk})

    class Meta:
        db_table = "customers"
        permissions = (
            ("view_customers", "Can View Orders"),
        )

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)


def format_full_address(street=None, street2=None, city=None, state=None, zip=None):
    full_address = ''
    if street and len(street):
        full_address = street
        if street2 and len(street2):
            full_address += " %s" % street2

    if city and len(city):
        if len(full_address):
            full_address += ", " + os.linesep
        full_address += city

    if state and len(state):
        if len(full_address):
            full_address += ", "
        full_address += state

    if zip and len(zip):
        if len(full_address):
            full_address += " "
        full_address += zip

    return full_address if len(full_address) > 0 else None

furnidashboard/customers/views.py
from django.views.generic import DetailView, UpdateView
from django.views.generic.edit import CreateView
from django_filters.rest_framework import DjangoFilterBackend
from django_tables2 import RequestConfig, SingleTableView
from rest_framework import views, status, viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from core.mixins import LoginRequiredMixin
from orders.forms import CustomerForm, CustomerDetailReadOnlyForm
from orders.tables import OrderTable
from customers.models import Customer
from .serializers import CustomerSerializer, MergeRecordsSerializer
from .tables import CustomersTable


class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Customer
    context_object_name = "customer"
    template_name = "customers/customer_update.html"
    form_class = CustomerForm


class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    context_object_name = "customer"
    template_name = "customers/customer_update.html"
    form_class = CustomerForm


class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer
    context_object_name = "customer"
    template_name = "customers/customer_detail.html"

    def get_context_data(self, **kwargs):
        context = super(CustomerDetailView, self).get_context_data(**kwargs)
        context['customer_details_form'] = CustomerDetailReadOnlyForm(instance=context['object'])

        customer_orders = context['object'].orders.all()
        customer_orders_table = OrderTable(customer_orders)
        RequestConfig(self.request).configure(customer_orders_table)
        context['customer_orders_table'] = customer_orders_table
        return context


class CustomerTableView(LoginRequiredMixin, SingleTableView):
    model = Customer
    table_class = CustomersTable
    template_name = "customers/customer_table.html"


class CustomerViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows customers to be viewed or edited.
    """
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    permission_classes = (IsAuthenticated,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['first_name', 'last_name', 'email', 'phone', 'mobile', 'bill_addr_city', 'bill_addr_state',]
    

class MergeRecordsView(views.APIView):
    serializer_class = MergeRecordsSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            primary_record_id = serializer.validated_data['primary']
            duplicate_record_ids = serializer.validated_data['duplicates']

            # Implement your logic to merge records with primary_record_id and duplicate_record_ids

            # Example logic: Merging by updating the primary record and deleting the duplicates
            # Implement your specific merge logic here

            return Response({'detail': 'Records merged successfully'}, status=status.HTTP_200_OK)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

furnidashboard/templates/customers/_customer_form.html
{% load bootstrap3 %}



        <div class="row">
          <div class="col-md-3">{% bootstrap_field form.tags %}</div>
        </div>

        <div class="well">
            <div class="row">
                <div class="col-md-3">
                    {% bootstrap_field form.first_name  %}
                </div>
                <div class="col-md-3">
                    {% bootstrap_field form.last_name  %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {% bootstrap_field form.mobile %}
                </div>
                <div class="col-md-3">{% bootstrap_field form.phone %}</div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {% bootstrap_field form.email %}
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
          <div class="col-md-6">
            <fieldset>
              <legend>Billing Address</legend>
              <div class="col-md-8">{% bootstrap_field form.bill_addr_str show_label=False %}</div>
              <div class="col-md-4">{% bootstrap_field form.bill_addr_str2 show_label=False %}</div>
              <div class="col-md-6">{% bootstrap_field form.bill_addr_city show_label=False %}</div>
              <div class="col-md-3">{% bootstrap_field form.bill_addr_state show_label=False %}</div>
              <div class="col-md-3">{% bootstrap_field form.bill_addr_zip show_label=False %}</div>
            </fieldset>
          </div>
          <div class="col-md-6">
            <fieldset>
              <legend>Shipping Address</legend>
              <div class="col-md-8">{% bootstrap_field form.ship_addr_str show_label=False %}</div>
              <div class="col-md-4">{% bootstrap_field form.ship_addr_str2 show_label=False %}</div>
              <div class="col-md-6">{% bootstrap_field form.ship_addr_city show_label=False %}</div>
              <div class="col-md-3">{% bootstrap_field form.ship_addr_state show_label=False %}</div>
              <div class="col-md-3">{% bootstrap_field form.ship_addr_zip show_label=False %}</div>
              <label for="shippingSameAsBilling">
                  <input type="checkbox" id="shippingSameAsBilling" name="shippingSameAsBilling"/> Same as Billing
                </label>
            </fieldset>
          </div>
        </div>

        <br/>
        <fieldset>
          <legend>Additional Info</legend>
          <div class="row">
            <div class="col-md-3">{% bootstrap_field form.company %}</div>
          </div>
          <div class="row">
            <div class="col-md-6">{% bootstrap_field form.notes %}</div>
          </div>
        </fieldset>

        <hr/>

        <h4>Full Address (do not edit)</h4>
        <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.shipping_address %}
            </div>
            <div class="col-md-6">
                {% bootstrap_field form.billing_address %}
            </div>
        </div>

furnidashboard/templates/customers/customer_detail.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load render_table from django_tables2 %}

{% block title %} Customer Info{% endblock %}

{% block page_title %} Customer: {{customer}}{% endblock page_title %}
{% block extra_js %}
  {{ form.media }}
{% endblock extra_js %}
{% block extra_css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
{% endblock %}

{% block content %}

  <div class="well"><a href="{% url 'customer_edit' object.pk %}" title="Edit Customer">Edit Customer</a></div>
  <hr/>


  <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Customer Details</h3>
      </div>
      <div class="panel-body">
          <div class="row customer-info">
              <div class="col-md-5" style="font-size: 2em;line-height: 130%">
                  {{ customer }}<br/>
                  <i class="fa fa-phone" aria-hidden="true"></i> 
                  {% if customer.mobile %} m.{{ customer.mobile }} {% endif %}
                  {% if customer.phone %} h.{{ customer.phone }} {% endif %} <br/>
                  <i class="fa fa-envelope" aria-hidden="true"></i> {{ customer.email }}
              </div>
              <div class="col-md-3">
                  <h4>Billing Address:</h4>
                  {{ customer.billing_address }}
              </div>
              <div class="col-md-3">
                  <h4>Shipping Address:</h4>
                  {{ customer.shipping_address }}
                  <br/><br/>
                  {% if customer.tags.all %}
                  <div class="tag-list">Tags: 
                      {% for tag in customer.tags.all %}
                          <span class="tagname"> {{ tag.name }} | </span>
                      {% endfor %}
                      </div>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>

  <h3>Orders History:</h3>
  <div id="order-list">
    {% render_table customer_orders_table %}
  </div>

{% endblock content %}

furnidashboard/templates/customers/customer_list.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% block title %}Customers{% endblock %}

{% block page_title %}Customers{% endblock page_title %}

{% block content %}

  <div>
      <ul>
      {% for object in object_list %}
      <li>{{ object }} | <a href="{% url "customer_edit" object.pk %}">Edit</a></li>
      {% endfor %}
      </ul>
  </div>

{% endblock content %}

furnidashboard/templates/customers/customer_table.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% block title %}Customers{% endblock %}
{% block extra_css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
{% endblock %}

{% block page_title %}Customer List{% endblock page_title %}

{% block content %}
  <div id="order-list" class="customer-list">

    {% render_table table %}

  </div>
{% endblock %}

furnidashboard/templates/customers/customer_update.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Update Customer{% endblock %}

{% block page_title %}Edit Customer Information: <i style="font-style: italic">{{customer}}</i>{% endblock page_title %}
{% block extra_js %}
  {{ form.media }}

  <script type="text/javascript">
        $(function () {
          $(document).ready(function () {
            $("#shippingSameAsBilling").on("change", function() {
              let shippingSameAsBilling = $(this).prop("checked") == true;
              if (shippingSameAsBilling) {
                  $("#id_ship_addr_str").val($("#id_bill_addr_str").val());
                  $("#id_ship_addr_str2").val($("#id_bill_addr_str2").val());
                  $("#id_ship_addr_city").val($("#id_bill_addr_city").val());
                  $("#id_ship_addr_state").val($("#id_bill_addr_state").val());
                  $("#id_ship_addr_zip").val($("#id_bill_addr_zip").val());
              }
            });
          });
        })
  </script>

{% endblock extra_js %}

{% block content %}

  <form action="" method="POST" id="orderForm" role="form" class="form">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.management_form }}
    {% bootstrap_form_errors form %}

    {% include "customers/_customer_form.html" with form=form %}

    <input type="submit" id="submitButton" class="btn btn-primary btn-large" value="Save"/>

  </form>

{% endblock content %}